version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: BankDB
    volumes:
      - mysql-bankapp:/var/lib/mysql
    networks:
      - bankapp
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pTest@123"]
      interval: 10s
      timeout: 5s
      retries: 3

  bankapp:
    image: bankapp-mini
    container_name: bankapp-mini
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/BankDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_PASSWORD: Test@123
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - bankapp
    restart: always

  nginx:
    image: nginx:1.23.3-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bankapp
    networks:
      - bankapp

volumes:
  mysql-bankapp:

networks:
  bankapp:
